### ISSUE TITLE
Components with variant in the theme file doesn't work without declarations

### ISSUE THREAD

**Issue by maximegelinas** [strawberrysass/strawberry#3]
This code should work, but it produced no CSS.

````scss
@include component(
  $name: 'my-cmp', 
  ) {

  @include component-variant(
    $name: 'my-cmp-variant',
    $declarations: (...)
    );

}
````

**Comment by maximegelinas** [comment]
For now the following syntax works fine: 

````scss
@include component(
  $name: 'my-cmp', 
  $declarations: ('null':'null')
  ) {

  @include component-variant(
    $name: 'my-cmp-variant',
    $declarations: (...)
    );

}
````
